name: EventDeblur_GOPRO
model_type: EventDiffusionModel
scale: 1
num_gpu: 1
manual_seed: 0

# Dataset settings
datasets:
  train:
    name: GOPRO
    type: EventDeblurDataset
    dataroot: /scratch/datasets/GoPro/GOPRO_Large/train
    phase: train
    gt_size: 256
    use_flip: true
    use_rot: true
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 8
    
  val:
    name: GOPRO
    type: EventDeblurDataset
    dataroot: /scratch/datasets/GoPro/GOPRO_Large/test
    phase: val
    gt_size: ~  # Use original size for validation
    use_flip: false
    use_rot: false
    use_shuffle: false
    num_worker_per_gpu: 2
    batch_size_per_gpu: 4

# Network settings
network_g:
  type: EventConditionedDiffusion
  
  # Diffusion parameters
  timesteps: 1000
  beta_schedule: cosine
  loss_type: l2
  
  # Event encoder parameters
  event_encoder:
    type: EventEncoder
    in_channels: 10  # 5 bins x 2 polarities
    mid_channels: 64
    out_channels: 64
    n_blocks: 4
  
  # UNet parameters
  unet:
    in_channels: 3
    model_channels: 64
    out_channels: 3
    num_res_blocks: 2
    attention_resolutions: [8, 16]
    dropout: 0.1
    channel_mult: [1, 2, 4, 8]
    time_embedding_dim: 128
    fusion_type: splice

# Path settings
path:
  pretrain_model_g: ~
  strict_load_g: true
  resume_state: ~

# Training settings
train:
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]
  
  scheduler:
    type: CosineAnnealingRestartLR
    periods: [200000, 200000, 200000, 200000]
    restart_weights: [1, 1, 1, 1]
    eta_min: !!float 1e-7
  
  total_iter: 800000
  warmup_iter: -1
  
  # Losses
  pixel_opt:
    type: L2Loss
    loss_weight: 1.0
    reduction: mean
  
# Validation settings
val:
  val_freq: 5000
  save_img: true
  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false

# Logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: 5000
  use_tb_logger: true
  wandb:
    project: EventDeblur
    resume_id: ~

# Distributed training settings
dist_params:
  backend: nccl
  port: 29500
